name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. Observe error '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide your environment details.
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Python version: [e.g., 3.11.5]
        - Proofloop version: [e.g., 0.1.0]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant logs or error messages (use --verbose for detailed logs).
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
