name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area of the project does this affect?
      options:
        - CLI Interface
        - Pipeline/Orchestration
        - MCP Integration
        - Research Mode
        - Verification System
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples.
